# Generated by Django 4.2.6 on 2023-11-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlist',
            name='modified_date',
        ),
    ]
