# Generated by Django 4.2.6 on 2023-11-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postlist', '0006_alter_board_author_alter_board_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
