# Generated by Django 4.2.6 on 2023-11-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postlist', '0007_alter_board_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
