# Generated by Django 4.2.6 on 2023-11-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postlist', '0010_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
