# Generated by Django 4.2.6 on 2023-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postlist', '0011_rename_author_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
